### ISSUE TITLE
Can more custom live streams be added?

### ISSUE THREAD

**Issue by 56025192** [ossrs/oryx#172]
**What is the business background? Please provide a description.**
Who are the users? How do they utilize this feature? What problem does this feature address?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
