### ISSUE TITLE
How to create multiple virtual live streams.

### ISSUE THREAD

**Issue by jonnyman12345** [ossrs/oryx#177]
**What is the business background? Please provide a description.**
Who are the users? How do they utilize this feature? What problem does this feature address?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
