### ISSUE TITLE
Cant play SRT url link in VLC

### ISSUE THREAD

**Issue by gasguti** [ossrs/oryx#186]
**Describe the bug**
Im using SRT with OBS, the problem is I cant play the SRT URL in VLC,  but the other links HTTP-FLV stream, HLS stream, webrtc works fine.
The url is srt://64.176.10.27:10080?streamid=#!::r=live/ncmjed?secret=20628c23090e49ec96d2175081c13447,m=publish
**Version**
[v5.14.19]

**Screenshots**
![image](https://github.com/ossrs/oryx/assets/57552531/79311a06-dceb-4dd3-8a8f-a1aab3ab9980)

thank you

**Comment by suzp1984** [comment]
you need to input `streamid` manually in `vlc'`'s preference settings.
make sure you installed the latest version of VLC first. My version is 3.0.20.
go to, settings -> show all -> stream output -> access output -> SRT, there is an input with label `SRT Stream ID`, you need to input it.

In your case, the url `srt://64.176.10.27:10080?streamid=#!::r=live/ncmjed?secret=20628c23090e49ec96d2175081c13447,m=publish` is the publish URL, the stream id you need to input is:
`#!::r=live/ncmjed,m=request`. Or in Oryx, it remind you to add `latency=20`, which means the streamid is `#!::r=live/ncmjed,latency=20,m=request`, it ok without it. 

> <img width="777" alt="Screenshot 2024-05-30 at 3 02 01 PM" src="https://github.com/ossrs/oryx/assets/2757043/8e33c9f2-fc36-4e92-9c3c-dddd84b33261">

Then in Network URL input, you just need to input the IP and port with scheme, in your case is `srt://64.176.10.27:10080`.

**Comment by gasguti** [comment]
thank you @suzp1984
