### ISSUE TITLE
Stream from Dahua Camera to RTMP server not possible

### ISSUE THREAD

**Issue by tommy-sch** [ossrs/oryx#189]
**What is the business background? Please provide a description.**
Want to stream directly from Dahua via RTMP function.
Dahua does not want symbols like % = ? in the stream URL.

**Is your feature request related to a problem? Please describe.**
Dahua does not want symbols like % = ? in the stream URL.
It is not possible to stream.

**Describe the solution you'd like**
Option to remove symbols from RTMP URL

**Describe alternatives you've considered**
RTSP is not possible because of network structure

**Additional context**

**Comment by suzp1984** [comment]
You can close the the `http hooks feature` to workaround the Camera limitation, while the payback is to sacrifice the media stream Authorization.

add `-e SRS_VHOST_HTTP_HOOKS_ENABLED=off` to the docker cmd.
the full cmd:
`docker run -it --name oryx -v $HOME/data:/data -p 80:2022 -p 443:2443 -p 1935:1935 -p 8000:8000/udp -p 10080:10080/udp -e SRS_VHOST_HTTP_HOOKS_ENABLED=off registry.cn-hangzhou.aliyuncs.com/ossrs/oryx:5`

**Comment by tommy-sch** [comment]
well I can now stream to the server. But I'am only getting the stream over the simple player.  not Xigua Payer or any other his player

**Comment by tommy-sch** [comment]
Well that works. But I only can get the .m3u8 if I create a Live Room, which is not a problem.
Does Live Rooms delete itself after time?, because that would be a problem.
Is it possible to get a snapshot url for the stream?

**Comment by suzp1984** [comment]
> Does Live Rooms delete itself after time?, because that would be a problem.
No, I don't think so.

> Is it possible to get a snapshot url for the stream?
I don't understand what the `snapshot url` mean?
The RTMP|webrtc|hls|http-flv|http-ts urls  are there, you can play the media stream by any client that can support any of above streaming protocol.
