### ISSUE TITLE
How can I add more streams to a multi-platform streaming setup that by default only supports three streams? Thank you!

### ISSUE THREAD

**Issue by topkof** [ossrs/oryx#198]
How can I increase the number of channels on a multiplatform pushstream system that defaults to three channels? Additionally, if there is no visual indicator for the maximum number of stream paths that can be added, would it be possible to implement a feature to add more paths? If paths are added manually, what is the correct procedure for inputting the keycode?
![multiplatform pushstream](https://github.com/ossrs/oryx/assets/26196829/b22c8e4d-74ae-4743-b946-4d00e0feec67)

**Comment by winlinvip** [comment]
Upgrade to v5.15.5+, see https://github.com/ossrs/oryx/releases
